# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uum.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(331, 440)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, -20, 341, 461))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("pyqt5\\dist\\build\\pkg\\back.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 311, 41))
        self.label_2.setStyleSheet("font: 87 18pt \"Nougat\";\n"
"color: white;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(70, 180, 181, 51))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    box-shadow: 0px 7px 25px yellow;\n"
"    background:linear-gradient(to bottom, #f0c911 5%, #f2ab1e 100%);\n"
"    background-color:#f0c911;\n"
"    border-radius:25px;\n"
"    padding: 15px;\n"
"    border:4px solid #AF1F00;\n"
"    text-shadow: -1px 0 #AF1F00, 0 2px #AF1F00, 2px 0 #AF1F00, 0 -1px #AF1F00;\n"
"    display:inline-block;\n"
"    cursor:pointer;\n"
"    color: white;\n"
"    font-size: 21px;\n"
"    font-family:\'Nougat\';\n"
"    font-weight:bold;\n"
"    padding:6px 24px;\n"
"    text-decoration:none;\n"
"}\n"
"QPushButton:hover {\n"
"    background:linear-gradient(to bottom, #f2ab1e 5%, #f0c911 100%);\n"
"    background-color:#f2ab1e;\n"
"}\n"
"QPushButton:pressed {\n"
"    position:relative;\n"
"    top:1px;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "UUM"))
        self.label_2.setText(_translate("Form", "Unlimited Mortis Super"))
        self.pushButton.setText(_translate("Form", "Bebra Super"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
